import {
  Command10Power,
  CommandAC,
  CommandCbrt,
  CommandCube,
  CommandDivision,
  CommandE,
  CommandEqual,
  CommandExp,
  CommandFactorial,
  CommandMemoryCall,
  CommandMemoryClean,
  CommandMemorySubtraction,
  CommandMemorySum,
  CommandMultiple,
  CommandNthRoot,
  CommandNumber,
  CommandPercent,
  CommandPI,
  CommandPlug,
  CommandPoint,
  CommandPower,
  CommandRatio,
  CommandRevertSign,
  CommandSqrt,
  CommandSquare,
  CommandSubtraction,
  CommandUndo,
} from '../command';
import { CommandSum } from '../command/commands/command-sum';

export const databaseButtons = [
  {
    value: 'UNDO',
    type: 'calculatorButtonForOtherOperation',
    command: CommandUndo,
    widthCell: 2,
  },
  {
    value: 'mc',
    type: 'calculatorButtonForOtherOperation',
    command: CommandMemoryClean,
  },
  {
    value: 'm+',
    type: 'calculatorButtonForOtherOperation',
    command: CommandMemorySum,
  },
  {
    value: 'm-',
    type: 'calculatorButtonForOtherOperation',
    command: CommandMemorySubtraction,
  },
  {
    value: 'mr',
    type: 'calculatorButtonForOtherOperation',
    command: CommandMemoryCall,
  },
  {
    value: 'AC',
    type: 'calculatorButtonForMainOperation',
    command: CommandAC,
  },
  {
    value: '±',
    type: 'calculatorButtonForOtherOperation',
    command: CommandRevertSign,
  },
  {
    value: '%',
    type: 'calculatorButtonForOtherOperation',
    command: CommandPercent,
  },
  {
    value: '÷',
    type: 'calculatorButtonForMainOperation',
    command: CommandDivision,
  },
  {
    value: '2',
    afterUp: 'nd',
    type: 'calculatorButtonForOtherOperation',
    command: CommandPlug,
  },
  {
    value: 'x',
    afterUp: '2',
    type: 'calculatorButtonForOtherOperation',
    command: CommandSquare,
  },
  {
    value: 'x',
    afterUp: '3',
    type: 'calculatorButtonForOtherOperation',
    command: CommandCube,
  },
  {
    value: 'x',
    afterUp: 'y',
    type: 'calculatorButtonForOtherOperation',
    command: CommandPower,
  },
  {
    value: 'e',
    afterUp: 'x',
    type: 'calculatorButtonForOtherOperation',
    command: CommandExp,
  },
  {
    value: '10',
    afterUp: 'x',
    type: 'calculatorButtonForOtherOperation',
    command: Command10Power,
  },
  {
    value: '7',
    type: 'calculatorButtonForNumber',
    command: CommandNumber,
  },
  {
    value: '8',
    type: 'calculatorButtonForNumber',
    command: CommandNumber,
  },
  {
    value: '9',
    type: 'calculatorButtonForNumber',
    command: CommandNumber,
  },
  {
    value: '×',
    type: 'calculatorButtonForMainOperation',
    command: CommandMultiple,
  },
  {
    value: '/',
    beforeUp: '1',
    afterDown: 'x',
    type: 'calculatorButtonForOtherOperation',
    command: CommandRatio,
  },
  {
    value: '√x',
    type: 'calculatorButtonForOtherOperation',
    command: CommandSqrt,
  },
  {
    value: '∛x',
    type: 'calculatorButtonForOtherOperation',
    command: CommandCbrt,
  },
  {
    value: '√x',
    beforeUp: 'y',
    type: 'calculatorButtonForOtherOperation',
    command: CommandNthRoot,
  },
  {
    value: 'ln',
    type: 'calculatorButtonForOtherOperation',
    command: CommandPlug,
  },
  {
    value: 'log',
    afterDown: '10',
    type: 'calculatorButtonForOtherOperation',
    command: CommandPlug,
  },
  {
    value: '4',
    type: 'calculatorButtonForNumber',
    command: CommandNumber,
  },
  {
    value: '5',
    type: 'calculatorButtonForNumber',
    command: CommandNumber,
  },
  {
    value: '6',
    type: 'calculatorButtonForNumber',
    command: CommandNumber,
  },
  {
    value: '-',
    type: 'calculatorButtonForMainOperation',
    command: CommandSubtraction,
  },
  {
    value: 'x!',
    type: 'calculatorButtonForOtherOperation',
    command: CommandFactorial,
  },
  {
    value: 'sin',
    type: 'calculatorButtonForOtherOperation',
    command: CommandPlug,
  },
  {
    value: 'cos',
    type: 'calculatorButtonForOtherOperation',
    command: CommandPlug,
  },
  {
    value: 'tan',
    type: 'calculatorButtonForOtherOperation',
    command: CommandPlug,
  },
  {
    value: 'e',
    type: 'calculatorButtonForOtherOperation',
    command: CommandE,
  },
  {
    value: 'EE',
    type: 'calculatorButtonForOtherOperation',
    command: CommandPlug,
  },
  {
    value: '1',
    type: 'calculatorButtonForNumber',
    command: CommandNumber,
  },
  {
    value: '2',
    type: 'calculatorButtonForNumber',
    command: CommandNumber,
  },
  {
    value: '3',
    type: 'calculatorButtonForNumber',
    command: CommandNumber,
  },
  {
    value: '+',
    type: 'calculatorButtonForMainOperation',
    command: CommandSum,
  },
  {
    value: 'Rad',
    type: 'calculatorButtonForOtherOperation',
    command: CommandPlug,
  },
  {
    value: 'sinh',
    type: 'calculatorButtonForOtherOperation',
    command: CommandPlug,
  },
  {
    value: 'cosh',
    type: 'calculatorButtonForOtherOperation',
    command: CommandPlug,
  },
  {
    value: 'tanh',
    type: 'calculatorButtonForOtherOperation',
    command: CommandPlug,
  },
  {
    value: '𝛑',
    type: 'calculatorButtonForOtherOperation',
    command: CommandPI,
  },
  {
    value: 'Rand',
    type: 'calculatorButtonForOtherOperation',
    command: CommandPlug,
  },
  {
    value: '0',
    type: 'calculatorButtonForNumber',
    command: CommandNumber,
    widthCell: 2,
  },
  {
    value: ',',
    type: 'calculatorButtonForNumber',
    command: CommandPoint,
  },
  {
    value: '=',
    type: 'calculatorButtonForMainOperation',
    command: CommandEqual,
  },
];
