import {
  Command10Power,
  CommandAC,
  CommandCbrt,
  CommandCube,
  CommandDivision,
  CommandE,
  CommandEqual,
  CommandExp,
  CommandFactorial,
  CommandMemoryCall,
  CommandMemoryClean,
  CommandMemorySubtraction,
  CommandMemorySum,
  CommandMultiple,
  CommandNthRoot,
  CommandNumber,
  CommandPercent,
  CommandPI,
  CommandPlug,
  CommandPoint,
  CommandPower,
  CommandRatio,
  CommandRevertSign,
  CommandSqrt,
  CommandSquare,
  CommandSubtraction,
  CommandUndo,
} from '../command';
import { CommandSum } from '../command/commands/command-sum';
import {
  calculatorButtonForMainOperation,
  calculatorButtonForNumber,
  calculatorButtonForOtherOperation,
} from '../components';

export const databaseButtons = [
  {
    value: 'UNDO',
    functionUI: calculatorButtonForOtherOperation,
    command: CommandUndo,
    widthCell: 2,
  },
  {
    value: 'mc',
    functionUI: calculatorButtonForOtherOperation,
    command: CommandMemoryClean,
  },
  {
    value: 'm+',
    functionUI: calculatorButtonForOtherOperation,
    command: CommandMemorySum,
  },
  {
    value: 'm-',
    functionUI: calculatorButtonForOtherOperation,
    command: CommandMemorySubtraction,
  },
  {
    value: 'mr',
    functionUI: calculatorButtonForOtherOperation,
    command: CommandMemoryCall,
  },
  {
    value: 'AC',
    functionUI: calculatorButtonForMainOperation,
    command: CommandAC,
  },
  {
    value: '±',
    functionUI: calculatorButtonForOtherOperation,
    command: CommandRevertSign,
  },
  {
    value: '%',
    functionUI: calculatorButtonForOtherOperation,
    command: CommandPercent,
  },
  {
    value: '÷',
    functionUI: calculatorButtonForMainOperation,
    command: CommandDivision,
  },
  {
    value: '2',
    afterUp: 'nd',
    functionUI: calculatorButtonForOtherOperation,
    command: CommandPlug,
  },
  {
    value: 'x',
    afterUp: '2',
    functionUI: calculatorButtonForOtherOperation,
    command: CommandSquare,
  },
  {
    value: 'x',
    afterUp: '3',
    functionUI: calculatorButtonForOtherOperation,
    command: CommandCube,
  },
  {
    value: 'x',
    afterUp: 'y',
    functionUI: calculatorButtonForOtherOperation,
    command: CommandPower,
  },
  {
    value: 'e',
    afterUp: 'x',
    functionUI: calculatorButtonForOtherOperation,
    command: CommandExp,
  },
  {
    value: '10',
    afterUp: 'x',
    functionUI: calculatorButtonForOtherOperation,
    command: Command10Power,
  },
  { value: '7', functionUI: calculatorButtonForNumber, command: CommandNumber },
  { value: '8', functionUI: calculatorButtonForNumber, command: CommandNumber },
  { value: '9', functionUI: calculatorButtonForNumber, command: CommandNumber },
  {
    value: '×',
    functionUI: calculatorButtonForMainOperation,
    command: CommandMultiple,
  },
  {
    value: '/',
    beforeUp: '1',
    afterDown: 'x',
    functionUI: calculatorButtonForOtherOperation,
    command: CommandRatio,
  },
  {
    value: '√x',
    functionUI: calculatorButtonForOtherOperation,
    command: CommandSqrt,
  },
  {
    value: '∛x',
    functionUI: calculatorButtonForOtherOperation,
    command: CommandCbrt,
  },
  {
    value: '√x',
    beforeUp: 'y',
    functionUI: calculatorButtonForOtherOperation,
    command: CommandNthRoot,
  },
  {
    value: 'ln',
    functionUI: calculatorButtonForOtherOperation,
    command: CommandPlug,
  },
  {
    value: 'log',
    afterDown: '10',
    functionUI: calculatorButtonForOtherOperation,
    command: CommandPlug,
  },
  {
    value: '4',
    functionUI: calculatorButtonForNumber,
    command: CommandNumber,
  },
  {
    value: '5',
    functionUI: calculatorButtonForNumber,
    command: CommandNumber,
  },
  {
    value: '6',
    functionUI: calculatorButtonForNumber,
    command: CommandNumber,
  },
  {
    value: '-',
    functionUI: calculatorButtonForMainOperation,
    command: CommandSubtraction,
  },
  {
    value: 'x!',
    functionUI: calculatorButtonForOtherOperation,
    command: CommandFactorial,
  },
  {
    value: 'sin',
    functionUI: calculatorButtonForOtherOperation,
    command: CommandPlug,
  },
  {
    value: 'cos',
    functionUI: calculatorButtonForOtherOperation,
    command: CommandPlug,
  },
  {
    value: 'tan',
    functionUI: calculatorButtonForOtherOperation,
    command: CommandPlug,
  },
  {
    value: 'e',
    functionUI: calculatorButtonForOtherOperation,
    command: CommandE,
  },
  {
    value: 'EE',
    functionUI: calculatorButtonForOtherOperation,
    command: CommandPlug,
  },
  {
    value: '1',
    functionUI: calculatorButtonForNumber,
    command: CommandNumber,
  },
  {
    value: '2',
    functionUI: calculatorButtonForNumber,
    command: CommandNumber,
  },
  {
    value: '3',
    functionUI: calculatorButtonForNumber,
    command: CommandNumber,
  },
  {
    value: '+',
    functionUI: calculatorButtonForMainOperation,
    command: CommandSum,
  },
  {
    value: 'Rad',
    functionUI: calculatorButtonForOtherOperation,
    command: CommandPlug,
  },
  {
    value: 'sinh',
    functionUI: calculatorButtonForOtherOperation,
    command: CommandPlug,
  },
  {
    value: 'cosh',
    functionUI: calculatorButtonForOtherOperation,
    command: CommandPlug,
  },
  {
    value: 'tanh',
    functionUI: calculatorButtonForOtherOperation,
    command: CommandPlug,
  },
  {
    value: '𝛑',
    functionUI: calculatorButtonForOtherOperation,
    command: CommandPI,
  },
  {
    value: 'Rand',
    functionUI: calculatorButtonForOtherOperation,
    command: CommandPlug,
  },
  {
    value: '0',
    functionUI: calculatorButtonForNumber,
    command: CommandNumber,
    widthCell: 2,
  },
  {
    value: ',',
    functionUI: calculatorButtonForNumber,
    command: CommandPoint,
  },
  {
    value: '=',
    functionUI: calculatorButtonForMainOperation,
    command: CommandEqual,
  },
];
